"""
Spanish translation of the homepage.

build.py makes /es/index.html from index.html: it keeps the same styles,
scroll effects and tracking scripts, and swaps every English string below for
its Spanish version. Each pair is an exact piece of index.html. If the English
homepage changes and a pair no longer matches, the build prints a warning, so
update the pair (or add a new one) and build again.

Course titles, company names and technology names stay in English.
"""

PAIRS = [
    # ---------- head ----------
    ('<html lang="en">', '<html lang="es">'),
    ('<title>Erwin Mongui, Engineering Leader and Director of Technology in Toronto</title>',
     '<title>Erwin Mongui, líder de ingeniería y Director de Tecnología en Toronto</title>'),
    ('<meta name="description" content="Erwin Mongui, software engineering leader in Toronto: Director of Technology at Cedar Planters, Certified AI Engineer, 18+ years building customer platforms.">',
     '<meta name="description" content="Erwin Mongui, líder de ingeniería de software en Toronto: Director de Tecnología en Cedar Planters, ingeniero certificado en IA, más de 18 años construyendo plataformas.">'),
    ('<link rel="canonical" href="https://erwinmongui.com/">', '<link rel="canonical" href="https://erwinmongui.com/es/">'),
    ('<link rel="alternate" type="application/rss+xml" title="Erwin Mongui: case studies and writing" href="https://erwinmongui.com/feed.xml">',
     '<link rel="alternate" type="application/rss+xml" title="Erwin Mongui: casos y artículos" href="https://erwinmongui.com/es/feed.xml">'),
    ('<meta property="og:locale" content="en_CA">',
     '<meta property="og:locale" content="es_CO">\n<meta property="og:locale:alternate" content="en_CA">'),
    ('<meta property="og:url" content="https://erwinmongui.com/">', '<meta property="og:url" content="https://erwinmongui.com/es/">'),
    ('<meta property="og:title" content="Erwin Mongui, Engineering Leader and Director of Technology">',
     '<meta property="og:title" content="Erwin Mongui, líder de ingeniería y Director de Tecnología">'),
    ('<meta name="twitter:title" content="Erwin Mongui, Engineering Leader and Director of Technology">',
     '<meta name="twitter:title" content="Erwin Mongui, líder de ingeniería y Director de Tecnología">'),
    ('content="18+ years building customer-facing platforms and the teams that run them. Director of Technology at Cedar Planters, Certified AI Engineer, Toronto."',
     'content="Más de 18 años construyendo plataformas para clientes y los equipos que las operan. Director de Tecnología en Cedar Planters, ingeniero certificado en IA, Toronto."'),
    ('content="Erwin Mongui logo with the words Engineering leader, Director of Technology, Toronto, Canada"',
     'content="Logo de Erwin Mongui con las palabras Engineering leader, Director of Technology, Toronto, Canada"'),

    # ---------- skip link and menu script (the header and footer come from build.py) ----------
    ('<a class="skip" href="#about">Skip to content</a>', '<a class="skip" href="#about">Ir al contenido</a>'),
    ("open ? 'Close menu' : 'Open menu'", "open ? 'Cerrar menú' : 'Abrir menú'"),

    # ---------- hero ----------
    ('aria-label="Introduction"', 'aria-label="Presentación"'),
    ('>Engineering leader. Eighteen years of building the platforms behind customer-facing products, and the teams that run them.</p>',
     '>Líder de ingeniería. Dieciocho años construyendo las plataformas detrás de productos para clientes, y los equipos que las operan.</p>'),
    ('>Director of Technology at Cedar Planters. Certified AI Engineer. Based in Toronto.</p>',
     '>Director de Tecnología en Cedar Planters. Ingeniero certificado en IA. En Toronto.</p>'),
    ('<a class="btn btn-primary" href="#experience">See the work</a>', '<a class="btn btn-primary" href="#experience">Ver el trabajo</a>'),
    ('Scroll<i></i>', 'Desliza<i></i>'),

    # ---------- about ----------
    ('I have spent 18 years turning ambitious roadmaps into systems that hold up in production: owning architecture end to end, from cloud migration and CI/CD to microservices and data models, and growing engineers through mentorship and structured career paths. I care about deployment velocity, technical debt, and whether the team is getting better every quarter. Since 2024, as a Certified AI Engineer, I have been bringing machine learning and AI-assisted development into that work.',
     'Llevo 18 años convirtiendo planes ambiciosos en sistemas que funcionan en producción: siendo dueño de la arquitectura de punta a punta, desde migraciones a la nube y CI/CD hasta microservicios y modelos de datos, y haciendo crecer a ingenieros con mentoría y planes de carrera estructurados. Me importan la velocidad de despliegue, la deuda técnica y que el equipo mejore cada trimestre. Desde 2024, como ingeniero certificado en IA, llevo el aprendizaje automático y el desarrollo asistido por IA a ese trabajo.'),

    # ---------- experience ----------
    ('>Experience.</h2>', '>Experiencia.</h2>'),
    ('Five roles across four companies, from junior engineer in Bogotá to Director of Technology in the Greater Toronto Area.',
     'Cinco cargos en cuatro empresas, de ingeniero junior en Bogotá a Director de Tecnología en el área metropolitana de Toronto.'),
    ('>January 2024 to present<', '>Enero de 2024 a hoy<'),
    ('>Software Engineering Manager and Director of Technology<', '>Gerente de Ingeniería de Software y Director de Tecnología<'),
    ('>faster data retrieval and analysis after redesigning the data models<', '>más rápidas la consulta y el análisis de datos tras rediseñar los modelos de datos<'),
    ('<li>Lead cross-functional teams building scalable applications and own the full lifecycle, from requirements through deployment.</li>',
     '<li>Lidero equipos multidisciplinarios que construyen aplicaciones escalables y soy dueño de todo el ciclo de vida, desde los requisitos hasta el despliegue.</li>'),
    ('<li>Redesigned the data models behind analytical and operational workloads, making retrieval and analysis 20% faster.</li>',
     '<li>Rediseñé los modelos de datos detrás de las cargas analíticas y operativas, haciendo la consulta y el análisis un 20% más rápidos.</li>'),
    ('<li>Run continuous improvements to the website, using A/B testing and third-party API integrations to lift performance and functionality.</li>',
     '<li>Mejoro continuamente el sitio web con pruebas A/B e integraciones con APIs de terceros para aumentar su rendimiento y sus funcionalidades.</li>'),
    ('<li>Keep tracking pixels and scripts accurate so marketing works from complete data, and keep the site and applications secure and up to date.</li>',
     '<li>Mantengo precisos los píxeles y scripts de seguimiento para que marketing trabaje con datos completos, y mantengo el sitio y las aplicaciones seguros y actualizados.</li>'),

    ('>May 2019 to November 2022<', '>Mayo de 2019 a noviembre de 2022<'),
    ('>CTO and Software Engineering Team Lead<', '>CTO y líder del equipo de ingeniería de software<'),
    ('>lower infrastructure and maintenance costs after leading the cloud migration<', '>menos costos de infraestructura y mantenimiento tras liderar la migración a la nube<'),
    ('<li>Defined the technical strategy and owned architecture across several high-traffic, customer-facing products.</li>',
     '<li>Definí la estrategia técnica y fui dueño de la arquitectura de varios productos de alto tráfico para clientes.</li>'),
    ('<li>Led the migration from legacy infrastructure to the cloud, cutting infrastructure and maintenance costs in half.</li>',
     '<li>Lideré la migración de la infraestructura heredada a la nube, reduciendo a la mitad los costos de infraestructura y mantenimiento.</li>'),
    ('<li>Built continuous delivery pipelines with Jenkins and automated testing, so the team could deploy often while production got more stable.</li>',
     '<li>Construí pipelines de entrega continua con Jenkins y pruebas automatizadas, para que el equipo desplegara con frecuencia mientras producción se volvía más estable.</li>'),
    ('<li>Evolved the Python and Django microservice backend and launched 15+ REST APIs, reducing latency by 25%.</li>',
     '<li>Evolucioné el backend de microservicios en Python y Django y lancé más de 15 APIs REST, reduciendo la latencia un 25%.</li>'),
    ('<li>Hired, onboarded and grew engineers across backend and platform teams; metrics-driven prioritization raised delivery efficiency by 20%.</li>',
     '<li>Contraté, incorporé e hice crecer a ingenieros de los equipos de backend y plataforma; priorizar con métricas aumentó la eficiencia de entrega un 20%.</li>'),

    ('>July 2015 to July 2018<', '>Julio de 2015 a julio de 2018<'),
    ('>Lead Software Engineer<', '>Ingeniero de software líder<'),
    ('>less manual operational work through the automation initiatives I delivered<', '>menos trabajo operativo manual gracias a las automatizaciones que entregué<'),
    ("<li>Led the team that rebuilt the company's core customer-facing website, increasing user engagement by 25%.</li>",
     '<li>Lideré el equipo que reconstruyó el sitio web principal de la empresa para clientes, aumentando la interacción de los usuarios un 25%.</li>'),
    ('<li>Delivered automation that removed 70% of manual operational work.</li>',
     '<li>Entregué automatizaciones que eliminaron el 70% del trabajo operativo manual.</li>'),
    ('<li>Introduced Docker and Kubernetes, making deployments consistent and the platform more reliable.</li>',
     '<li>Introduje Docker y Kubernetes, haciendo los despliegues consistentes y la plataforma más confiable.</li>'),
    ('<li>Brought in Agile practices and coached junior engineers, improving delivery predictability and cutting operational costs by 25%.</li>',
     '<li>Implementé prácticas ágiles y acompañé a ingenieros junior, mejorando la previsibilidad de las entregas y reduciendo los costos operativos un 25%.</li>'),

    ('>May 2013 to June 2015<', '>Mayo de 2013 a junio de 2015<'),
    ('>Senior Software Engineer, consulting for Old Mutual and Editorial Legis<', '>Ingeniero de software senior, consultor para Old Mutual y Editorial Legis<'),
    ('>sales growth in the first year of the payment service I built for Old Mutual<', '>de crecimiento en ventas en el primer año del servicio de pagos que construí para Old Mutual<'),
    ("<li>Built Old Mutual's payment microservice on MVC .NET, which drove a 50% increase in sales in its first year.</li>",
     '<li>Construí el microservicio de pagos de Old Mutual en MVC .NET, que impulsó un aumento del 50% en ventas en su primer año.</li>'),
    ('<li>Delivered REST APIs on ASP.NET for Editorial Legis, improving content management efficiency by 40%.</li>',
     '<li>Entregué APIs REST en ASP.NET para Editorial Legis, mejorando la eficiencia de la gestión de contenidos un 40%.</li>'),
    ('<li>Introduced automated testing that kept existing applications at 98% stability, and optimized SQL for a 30% performance gain on large data volumes.</li>',
     '<li>Introduje pruebas automatizadas que mantuvieron las aplicaciones existentes en un 98% de estabilidad, y optimicé SQL para ganar un 30% de rendimiento con grandes volúmenes de datos.</li>'),
    ('<li>Designed normalized relational schemas and wrote the complex SQL that turned large datasets into decisions.</li>',
     '<li>Diseñé esquemas relacionales normalizados y escribí el SQL complejo que convirtió grandes conjuntos de datos en decisiones.</li>'),

    ('>February 2010 to June 2012<', '>Febrero de 2010 a junio de 2012<'),
    ('>Americas BPS, for Hewlett Packard Enterprise<', '>Americas BPS, para Hewlett Packard Enterprise<'),
    ('>Junior Software Engineer<', '>Ingeniero de software junior<'),
    ('>productivity gain from the applications I designed and built<', '>de aumento de productividad con las aplicaciones que diseñé y construí<'),
    ('<li>Designed and built C# and .NET applications that expanded system functionality and performance.</li>',
     '<li>Diseñé y construí aplicaciones en C# y .NET que ampliaron las funcionalidades y el rendimiento de los sistemas.</li>'),
    ('<li>Shipped multiple projects on time, with the attention to detail and organization that kept production accurate.</li>',
     '<li>Entregué varios proyectos a tiempo, con la atención al detalle y la organización que mantuvieron producción sin errores.</li>'),
    ('<li>Where the habit of writing well-documented, dependable code started.</li>',
     '<li>Donde empezó el hábito de escribir código confiable y bien documentado.</li>'),

    ('alt="Adevinta Culture Awards 2019 finalist digital diploma awarded to Erwin Mongui"',
     'alt="Diploma digital de finalista de los Adevinta Culture Awards 2019 otorgado a Erwin Mongui"'),
    ('>Adevinta Culture Awards finalist.</h3>', '>Finalista de los Adevinta Culture Awards.</h3>'),
    ("Recognized while I was CTO at Fincaraiz.com.co. The Culture Awards go to the people who build trust within their teams by living Adevinta's Key Behaviours:",
     'Reconocimiento recibido cuando era CTO de Fincaraiz.com.co. Los Culture Awards premian a las personas que generan confianza en sus equipos viviendo los comportamientos clave de Adevinta:'),
    ('<li>Say it like it is, and treat feedback as a gift.</li>', '<li>Decir las cosas como son, y tomar la retroalimentación como un regalo.</li>'),
    ("<li>Win and lose together, and don't be a jerk.</li>", '<li>Ganar y perder juntos, y no ser un idiota.</li>'),
    ('<li>Get stuff done and keep your promises.</li>', '<li>Sacar las cosas adelante y cumplir lo prometido.</li>'),
    ('<li>Always be learning, fast. Try stuff, learn from the data, and try again.</li>',
     '<li>Aprender siempre, y rápido. Probar, aprender de los datos y volver a intentar.</li>'),

    # ---------- case studies ----------
    ('<section class="stage stage-dark" id="case-studies" aria-labelledby="cases-h">', '<section class="stage stage-dark" id="casos" aria-labelledby="cases-h">'),
    ('>How the numbers happened.</h2>', '>Cómo se lograron los números.</h2>'),
    ('Three projects written up in full: the plan, the architecture, what went wrong and how the team got through it.',
     'Tres proyectos contados completos: el plan, la arquitectura, lo que salió mal y cómo lo superó el equipo.'),
    ('href="/work/fincaraiz-monolith-to-microservices/"', 'href="/es/casos/fincaraiz-monolito-a-microservicios/"'),
    ('href="/work/fincaraiz-lead-distribution/"', 'href="/es/casos/fincaraiz-distribucion-de-leads/"'),
    ('href="/work/cedar-planters-data-platform/"', 'href="/es/casos/cedar-planters-plataforma-de-datos/"'),
    ('<span class="cap">lower hosting cost, zero downtime</span>', '<span class="cap">menos costo de hosting, sin caídas</span>'),
    ('<h3>Monolith to microservices at Fincaraiz</h3>', '<h3>De monolito a microservicios en Fincaraiz</h3>'),
    ('<p>Moving a real estate portal with 5M+ monthly visits from ASP.NET to Django, React and Kubernetes, and rebuilding search on the way.</p>',
     '<p>La migración de un portal inmobiliario con más de 5 millones de visitas al mes de ASP.NET a Django, React y Kubernetes, reconstruyendo la búsqueda en el camino.</p>'),
    ('<span class="cap">of leads delivered and reconciled</span>', '<span class="cap">de los leads entregados y conciliados</span>'),
    ('<h3>A lead distribution engine for any CRM</h3>', '<h3>Un motor de distribución de leads para cualquier CRM</h3>'),
    ('<p>How a failed integration model became a Connector service that onboards partners in minutes, across six CRM platforms.</p>',
     '<p>Cómo un modelo de integración fallido se convirtió en un servicio Connector que integra aliados en minutos, en seis plataformas CRM.</p>'),
    ('<span class="num">Months &rarr; hours</span><span class="cap">to produce a new report</span>',
     '<span class="num">Meses &rarr; horas</span><span class="cap">para producir un reporte nuevo</span>'),
    ('<h3>A data platform from zero at Cedar Planters</h3>', '<h3>Una plataforma de datos desde cero en Cedar Planters</h3>'),
    ('<p>As the first technical hire, replacing third-party reporting tools and spreadsheets with one platform the company owns.</p>',
     '<p>Como primera contratación técnica, reemplazando herramientas de reportes de terceros y hojas de cálculo por una plataforma propia.</p>'),
    ('<span class="more">Read the case study &rarr;</span>', '<span class="more">Leer el caso &rarr;</span>'),
    ('<a class="hp-more" href="/work/">All case studies &rarr;</a>', '<a class="hp-more" href="/work/" hreflang="en" lang="en">Case studies in English &rarr;</a>'),

    # ---------- impact ----------
    ('>Measured in production.</h2>', '>Medido en producción.</h2>'),
    ('>A few of the numbers behind the roles.</p>', '>Algunos de los números detrás de cada cargo.</p>'),
    ('>years building software and leading the teams that build it</p>', '>años construyendo software y liderando los equipos que lo construyen</p>'),
    ('>2010 to today</p>', '>De 2010 a hoy</p>'),
    ('>lower infrastructure and maintenance costs after a cloud migration</p>', '>menos costos de infraestructura y mantenimiento tras una migración a la nube</p>'),
    ('>of manual operational work automated away</p>', '>del trabajo operativo manual automatizado</p>'),
    ('>lower latency across 15+ REST APIs on a Python microservice backend</p>', '>menos latencia en más de 15 APIs REST sobre un backend de microservicios en Python</p>'),
    ('>more user engagement after rebuilding the core customer website</p>', '>más interacción de los usuarios tras reconstruir el sitio web principal</p>'),
    ('>sales growth in the first year of a new payment service</p>', '>de crecimiento en ventas en el primer año de un nuevo servicio de pagos</p>'),

    # ---------- AI ----------
    ('>AI, in practice.</h2>', '>IA, en la práctica.</h2>'),
    ('Machine learning built on eighteen years of data-heavy platform work, and AI tools built into how the work gets done.',
     'Aprendizaje automático construido sobre dieciocho años de plataformas intensivas en datos, y herramientas de IA integradas en la forma de trabajar.'),
    ('<p class="ai-cert">Certified Artificial Intelligence Engineer, Lambton College, 2024</p>',
     '<p class="ai-cert">Ingeniero certificado en Inteligencia Artificial, Lambton College, 2024</p>'),
    ('<h3>Model building and training</h3>', '<h3>Construcción y entrenamiento de modelos</h3>'),
    ('<p>TensorFlow and PyTorch for building and training models, with Pandas, NumPy and Matplotlib doing the data preparation and analysis that every model depends on.</p>',
     '<p>TensorFlow y PyTorch para construir y entrenar modelos, con Pandas, NumPy y Matplotlib para la preparación y el análisis de datos de los que depende todo modelo.</p>'),
    ('<h3>Data foundations for AI</h3>', '<h3>Bases de datos para la IA</h3>'),
    ('<p>Models are only as good as the data underneath them. At Cedar Planters I built the data platform and redesigned the data models serving analytical and operational workloads, making retrieval 20% faster. At Fincaraiz I led natural language, map-aware property search years before the generative AI wave.</p>',
     '<p>Un modelo es tan bueno como los datos que lo sostienen. En Cedar Planters construí la plataforma de datos y rediseñé los modelos de datos de las cargas analíticas y operativas, haciendo la consulta un 20% más rápida. En Fincaraiz lideré una búsqueda inmobiliaria en lenguaje natural y basada en mapas, años antes de la ola de la IA generativa.</p>'),
    ('<span class="chip">Data architecture</span>', '<span class="chip">Arquitectura de datos</span>'),
    ('<h3>AI-assisted engineering</h3>', '<h3>Ingeniería asistida por IA</h3>'),
    ('<p>Cursor and Windsurf are part of the daily workflow: scaffolding, tests, refactors and exploration, held to the same review and testing bar as any other code that ships.</p>',
     '<p>Cursor y Windsurf son parte del trabajo diario: estructura inicial, pruebas, refactorizaciones y exploración, con la misma exigencia de revisión y pruebas que cualquier otro código que sale a producción.</p>'),
    ('<span class="chip">AI pair programming</span>', '<span class="chip">Programación en pareja con IA</span>'),
    ('<h3>Leading AI adoption</h3>', '<h3>Liderar la adopción de IA</h3>'),
    ("<p>An engineering manager's view of AI: where it removes toil, where it needs guardrails, and how to know it is working. Metrics-driven prioritization and A/B testing decide what stays.</p>",
     '<p>La mirada de un líder de ingeniería sobre la IA: dónde elimina trabajo repetitivo, dónde necesita salvaguardas y cómo saber si está funcionando. La priorización con métricas y las pruebas A/B deciden qué se queda.</p>'),
    ('<span class="chip">Metrics-driven prioritization</span>', '<span class="chip">Priorización con métricas</span>'),
    ('<span class="chip">A/B testing</span>', '<span class="chip">Pruebas A/B</span>'),
    ('<span class="chip">Developer experience</span>', '<span class="chip">Experiencia de desarrollo</span>'),
    ('<span class="chip">Engineering guardrails</span>', '<span class="chip">Salvaguardas de ingeniería</span>'),

    # ---------- writing ----------
    ('<section class="stage stage-light" id="writing" aria-labelledby="writing-h">', '<section class="stage stage-light" id="articulos" aria-labelledby="writing-h">'),
    ('>Notes from the job.</h2>', '>Notas del trabajo.</h2>'),
    ('What the projects taught me about architecture, tools, AI and leading engineers.',
     'Lo que me enseñaron los proyectos sobre arquitectura, herramientas, IA y liderazgo de ingenieros.'),
    ('<a class="hp-post" href="/writing/lead-time-cycle-time-bottlenecks/"><span class="tag">Delivery &middot; September 25, 2026</span><h3>Finding delivery bottlenecks with lead time and cycle time</h3><p>Lead time, cycle time and flow efficiency: five steps to find where work gets stuck, and the review bottleneck AI creates.</p></a>',
     '<a class="hp-post" href="/es/articulos/cuellos-de-botella-lead-time-cycle-time/"><span class="tag">Entrega &middot; 25 de septiembre de 2026</span><h3>Encontrar cuellos de botella en la entrega con lead time y cycle time</h3><p>Lead time, cycle time y eficiencia de flujo: cinco pasos para encontrar dónde se atasca el trabajo, y el cuello de botella en revisión que crea la IA.</p></a>'),
    ('<a class="hp-post" href="/writing/engineering-team-health-metrics/"><span class="tag">Leadership &middot; September 24, 2026</span><h3>How I measure engineering team health</h3><p>Delivery, health and impact metrics, how they map to DORA and SPACE, and how to tell whether AI assistants really help.</p></a>',
     '<a class="hp-post" href="/es/articulos/metricas-de-salud-de-equipos-de-ingenieria/"><span class="tag">Liderazgo &middot; 24 de septiembre de 2026</span><h3>Cómo mido la salud de un equipo de ingeniería</h3><p>Métricas de entrega, salud e impacto, cómo se relacionan con DORA y SPACE, y cómo saber si los asistentes de IA realmente ayudan.</p></a>'),
    ('<a class="hp-post" href="/writing/from-data-analyst-to-data-engineer/"><span class="tag">Leadership &middot; September 22, 2026</span><h3>From data analyst to data engineer, through one good question</h3><p>How one good question grew an engineer and improved our data pipelines, and where AI assistants fit in mentoring.</p></a>',
     '<a class="hp-post" href="/es/articulos/de-analista-de-datos-a-ingeniero-de-datos/"><span class="tag">Liderazgo &middot; 22 de septiembre de 2026</span><h3>De analista de datos a ingeniero de datos, gracias a una buena pregunta</h3><p>Cómo una buena pregunta hizo crecer a un ingeniero y mejoró nuestros pipelines de datos, y dónde encajan los asistentes de IA en la mentoría.</p></a>'),
    ('<a class="hp-post" href="/writing/choose-tools-your-team-can-support/"><span class="tag">Architecture &middot; September 21, 2026</span><h3>Pick the tool your team can support, not the one on the shortlist</h3><p>What a six-times overrun on single sign-on taught us: a tool-selection scorecard and how AI changes the trade-off.</p></a>',
     '<a class="hp-post" href="/es/articulos/elegir-herramientas-que-tu-equipo-pueda-sostener/"><span class="tag">Arquitectura &middot; 21 de septiembre de 2026</span><h3>Elige la herramienta que tu equipo puede sostener, no la que encabeza la lista</h3><p>Lo que nos enseñó un inicio de sesión único que tomó seis veces más: una matriz para elegir herramientas y cómo la IA cambia la decisión.</p></a>'),
    ('<a class="hp-more" href="/writing/">All writing &rarr;</a>', '<a class="hp-more" href="/es/articulos/">Todos los artículos &rarr;</a>'),

    # ---------- skills ----------
    ('>The stack.</h2>', '>El stack.</h2>'),
    ('Grouped by where it shows up in the work. Scroll sideways to browse.',
     'Agrupado según dónde aparece en el trabajo. Desliza hacia los lados para ver más.'),
    ('aria-label="Skill groups, scroll horizontally"', 'aria-label="Grupos de habilidades, desplázate horizontalmente"'),
    ('<h3>Machine learning and AI</h3>', '<h3>Aprendizaje automático e IA</h3>'),
    ('<p>Certified AI Engineer, Lambton College, 2024. Model building in TensorFlow and PyTorch, data work in the Python stack.</p>',
     '<p>Ingeniero certificado en IA, Lambton College, 2024. Construcción de modelos en TensorFlow y PyTorch, trabajo con datos en el stack de Python.</p>'),
    ('<h3>AI-assisted development</h3>', '<h3>Desarrollo asistido por IA</h3>'),
    ('<p>AI coding assistants as part of the everyday workflow, with the same review bar as any other code.</p>',
     '<p>Asistentes de programación con IA como parte del trabajo diario, con la misma exigencia de revisión que cualquier otro código.</p>'),
    ('<h3>Languages</h3>', '<h3>Lenguajes</h3>'),
    ('<p>The everyday tools, with Python and C# carrying most of the backend history.</p>',
     '<p>Las herramientas de todos los días, con Python y C# en la mayor parte de la historia del backend.</p>'),
    ('<h3>Backend and architecture</h3>', '<h3>Backend y arquitectura</h3>'),
    ('<p>Microservice platforms, REST APIs and the queues that keep them honest.</p>',
     '<p>Plataformas de microservicios, APIs REST y las colas que las mantienen en orden.</p>'),
    ('<span class="chip">Microservices</span>', '<span class="chip">Microservicios</span>'),
    ('<span class="chip">OOP</span>', '<span class="chip">POO</span>'),
    ('<p>Customer-facing web products, tuned with A/B tests and performance work.</p>',
     '<p>Productos web para clientes, afinados con pruebas A/B y trabajo de rendimiento.</p>'),
    ('<span class="chip">Web performance</span>', '<span class="chip">Rendimiento web</span>'),
    ('<h3>Cloud and DevOps</h3>', '<h3>Nube y DevOps</h3>'),
    ('<p>From legacy servers to cloud pipelines that deploy many times a day.</p>',
     '<p>De servidores heredados a pipelines en la nube que despliegan muchas veces al día.</p>'),
    ('<h3>Data and search</h3>', '<h3>Datos y búsqueda</h3>'),
    ('<p>Relational at the core, with document stores, caches and search where they fit.</p>',
     '<p>Relacional en el centro, con bases de documentos, cachés y búsqueda donde encajan.</p>'),
    ('<h3>Ways of working</h3>', '<h3>Formas de trabajo</h3>'),
    ('<p>Agile delivery, metrics-driven prioritization and the tooling around it.</p>',
     '<p>Entrega ágil, priorización con métricas y las herramientas que la acompañan.</p>'),
    ('<span class="chip">Agile</span>', '<span class="chip">Ágil</span>'),
    ('<h3>Leadership</h3>', '<h3>Liderazgo</h3>'),
    ('<p>Building teams that get better every quarter, and platforms that let them.</p>',
     '<p>Construir equipos que mejoran cada trimestre, y plataformas que se lo permiten.</p>'),
    ('<span class="chip">Technical strategy</span>', '<span class="chip">Estrategia técnica</span>'),
    ('<span class="chip">Architecture ownership</span>', '<span class="chip">Responsabilidad de la arquitectura</span>'),
    ('<span class="chip">Hiring and onboarding</span>', '<span class="chip">Contratación e incorporación</span>'),
    ('<span class="chip">Mentorship and coaching</span>', '<span class="chip">Mentoría y acompañamiento</span>'),
    ('<span class="chip">Performance management</span>', '<span class="chip">Gestión del desempeño</span>'),
    ('<span class="chip">Technical debt roadmaps</span>', '<span class="chip">Planes de deuda técnica</span>'),
    ('aria-label="Previous skill groups"', 'aria-label="Grupos anteriores"'),
    ('aria-label="Next skill groups"', 'aria-label="Grupos siguientes"'),

    # ---------- education ----------
    ('>Education.</h2>', '>Educación.</h2>'),
    ('<p class="edu-year">August 2024</p>', '<p class="edu-year">Agosto de 2024</p>'),
    ('<p class="edu-degree">Certified Artificial Intelligence Engineer</p>', '<p class="edu-degree">Ingeniero certificado en Inteligencia Artificial</p>'),
    ('<p class="edu-year">October 2013</p>', '<p class="edu-year">Octubre de 2013</p>'),
    ('<p class="edu-degree">Bachelor of Computer Engineering</p>', '<p class="edu-degree">Ingeniería de Computación</p>'),
    ('<p class="langs"><b>Spanish</b>, native. <b>English</b>, proficient.</p>', '<p class="langs"><b>Español</b>, nativo. <b>Inglés</b>, avanzado.</p>'),

    # ---------- certifications ----------
    ('>Licenses and certifications.</h2>', '>Licencias y certificaciones.</h2>'),
    ('Twenty-four credentials, grouped by what they sharpened. Each title opens the credential.',
     'Veinticuatro credenciales, agrupadas según lo que fortalecieron. Cada título abre la credencial (en inglés).'),
    ('<h3>Machine learning and data</h3>', '<h3>Aprendizaje automático y datos</h3>'),
    ('<h3>Fintech and agile delivery</h3>', '<h3>Fintech y entrega ágil</h3>'),
    ('<h3>Software architecture</h3>', '<h3>Arquitectura de software</h3>'),
    ('<h3>Data, search and infrastructure</h3>', '<h3>Datos, búsqueda e infraestructura</h3>'),
    (', January 2024</span>', ', enero de 2024</span>'),
    (', February 2022</span>', ', febrero de 2022</span>'),
    (', March 2022</span>', ', marzo de 2022</span>'),
    (', May 2021</span>', ', mayo de 2021</span>'),
    (', May 2023</span>', ', mayo de 2023</span>'),
    (', June 2016</span>', ', junio de 2016</span>'),
    (', July 2023</span>', ', julio de 2023</span>'),
    (', September 2023</span>', ', septiembre de 2023</span>'),
    (', October 2023</span>', ', octubre de 2023</span>'),
    (', November 2023</span>', ', noviembre de 2023</span>'),
    (', December 2023</span>', ', diciembre de 2023</span>'),

    # ---------- quick facts ----------
    ('>Quick facts.</h2>', '>Preguntas frecuentes.</h2>'),
    ('The short answers, for anyone who arrived here with a question.', 'Las respuestas cortas, para quien llegó aquí con una pregunta.'),
    ('<h3>Who is Erwin Mongui?</h3>', '<h3>¿Quién es Erwin Mongui?</h3>'),
    ('<p>Erwin Mongui is a software engineering leader based in Toronto, Ontario, Canada. He is Director of Technology and Software Engineering Manager at Cedar Planters, and a Certified Artificial Intelligence Engineer. He has 18+ years of experience building customer-facing platforms and leading the teams that run them.</p>',
     '<p>Erwin Mongui es un líder de ingeniería de software colombiano radicado en Toronto, Ontario, Canadá. Es Director de Tecnología y Gerente de Ingeniería de Software en Cedar Planters, e ingeniero certificado en Inteligencia Artificial. Tiene más de 18 años de experiencia construyendo plataformas para clientes y liderando los equipos que las operan.</p>'),
    ('<h3>What migration did Erwin Mongui lead at Fincaraiz?</h3>', '<h3>¿Qué migración lideró Erwin Mongui en Fincaraiz?</h3>'),
    ('<p>As CTO of Fincaraiz.com.co he led a team of 30 through the move from a legacy ASP.NET monolith to Django and React microservices on Kubernetes, for a real estate portal with more than 5 million monthly visits. The migration ran with zero downtime, cut hosting and maintenance costs by 50%, and rebuilt search with natural language and map-aware matching.</p>',
     '<p>Como CTO de Fincaraiz.com.co lideró a un equipo de 30 personas en el paso de un monolito ASP.NET heredado a microservicios con Django y React sobre Kubernetes, para un portal inmobiliario con más de 5 millones de visitas al mes. La migración se hizo sin caídas, redujo un 50% los costos de hosting y mantenimiento, y reconstruyó la búsqueda con lenguaje natural y coincidencia geográfica.</p>'),
    ('<h3>Has Erwin Mongui published research?</h3>', '<h3>¿Erwin Mongui ha publicado investigación?</h3>'),
    ('<p>Yes. He co-authored “Eliminating Randomness in Selecting International Passengers for RT-PCR” with Umid Ghimire, Dharmik Limbani and Sairam Kilari at Lambton College, for the STEM Fellowship Big Data and AI Challenge 2023. It was published in the STEM Fellowship Journal (doi:10.17975/sfj-2023-007).</p>',
     '<p>Sí. Es coautor de “Eliminating Randomness in Selecting International Passengers for RT-PCR”, con Umid Ghimire, Dharmik Limbani y Sairam Kilari en Lambton College, para el STEM Fellowship Big Data and AI Challenge 2023. Se publicó en el STEM Fellowship Journal (doi:10.17975/sfj-2023-007).</p>'),
    ('<h3>Does Erwin Mongui speak Spanish?</h3>', '<h3>¿Erwin Mongui habla español?</h3>'),
    ('<p>Yes. Spanish is his native language and he works professionally in English. He built the first part of his career in Bogotá, Colombia, before moving to Toronto in 2022.</p>',
     '<p>Sí. El español es su lengua materna y trabaja profesionalmente en inglés. Construyó la primera parte de su carrera en Bogotá, Colombia, antes de mudarse a Toronto en 2022.</p>'),
    ('<h3>What does Erwin Mongui do at Cedar Planters?</h3>', '<h3>¿Qué hace Erwin Mongui en Cedar Planters?</h3>'),
    ("<p>Since January 2024 he has led Cedar Planters' engineering as Software Engineering Manager and Director of Technology in Oakville, Ontario. He owns the full software lifecycle from requirements through deployment, redesigned the data models behind analytical and operational workloads for 20% faster retrieval, and runs continuous improvement of the website through A/B testing and third-party integrations.</p>",
     '<p>Desde enero de 2024 lidera la ingeniería de Cedar Planters como Gerente de Ingeniería de Software y Director de Tecnología en Oakville, Ontario. Es dueño de todo el ciclo de vida del software, desde los requisitos hasta el despliegue; rediseñó los modelos de datos de las cargas analíticas y operativas para consultas un 20% más rápidas, y mejora continuamente el sitio web con pruebas A/B e integraciones con terceros.</p>'),
    ("<h3>What is Erwin Mongui's background before Cedar Planters?</h3>", '<h3>¿Cuál es la trayectoria de Erwin Mongui antes de Cedar Planters?</h3>'),
    ('<p>He was CTO and Software Engineering Team Lead at Fincaraiz.com.co in Bogotá (2019 to 2022), where he led a cloud migration that halved infrastructure costs and shipped 15+ REST APIs on a Python and Django microservice backend. Earlier he was Lead Software Engineer at Fincaraiz.com.co (2015 to 2018), Senior Software Engineer at Periferia IT consulting for Old Mutual and Editorial Legis (2013 to 2015), and Junior Software Engineer at Americas BPS for Hewlett Packard Enterprise (2010 to 2012).</p>',
     '<p>Fue CTO y líder del equipo de ingeniería de software en Fincaraiz.com.co en Bogotá (2019 a 2022), donde lideró una migración a la nube que redujo a la mitad los costos de infraestructura y lanzó más de 15 APIs REST sobre un backend de microservicios en Python y Django. Antes fue ingeniero de software líder en Fincaraiz.com.co (2015 a 2018), ingeniero de software senior en Periferia IT, como consultor para Old Mutual y Editorial Legis (2013 a 2015), e ingeniero de software junior en Americas BPS para Hewlett Packard Enterprise (2010 a 2012).</p>'),
    ("<h3>What is Erwin Mongui's education?</h3>", '<h3>¿Qué estudió Erwin Mongui?</h3>'),
    ('<p>Erwin Mongui holds a Bachelor of Computer Engineering from Fundación Universitaria Los Libertadores in Bogotá (2013) and is a Certified Artificial Intelligence Engineer from Lambton College in Toronto (2024). He is also a Scrum Master Certified (SMC) professional.</p>',
     '<p>Erwin Mongui es ingeniero de computación de la Fundación Universitaria Los Libertadores en Bogotá (2013) e ingeniero certificado en Inteligencia Artificial de Lambton College en Toronto (2024). También es Scrum Master certificado (SMC).</p>'),
    ('<h3>What technologies does Erwin Mongui work with?</h3>', '<h3>¿Con qué tecnologías trabaja Erwin Mongui?</h3>'),
    ('<p>Python, Django, C#, .NET, Node.js, React and TypeScript for building; AWS, Docker, Kubernetes, Jenkins and Spinnaker for shipping; PostgreSQL, MySQL, MongoDB, Redis, Elasticsearch, OpenSearch, Apache Solr and Apache NiFi for data and search; and TensorFlow, PyTorch, Pandas and NumPy for machine learning, with Cursor and Windsurf for AI-assisted development.</p>',
     '<p>Python, Django, C#, .NET, Node.js, React y TypeScript para construir; AWS, Docker, Kubernetes, Jenkins y Spinnaker para desplegar; PostgreSQL, MySQL, MongoDB, Redis, Elasticsearch, OpenSearch, Apache Solr y Apache NiFi para datos y búsqueda; y TensorFlow, PyTorch, Pandas y NumPy para aprendizaje automático, con Cursor y Windsurf para el desarrollo asistido por IA.</p>'),

    # ---------- contact ----------
    ('<section class="stage stage-dark" id="contact" aria-labelledby="contact-h">', '<section class="stage stage-dark" id="contacto" aria-labelledby="contact-h">'),
    (">Let's talk.</h2>", '>Hablemos.</h2>'),
    ("Whether you're scaling a platform or building the team that runs it, I'd like to hear about it.",
     'Si estás escalando una plataforma o formando el equipo que la opera, me gustaría conocer tu proyecto.'),
    ('<a class="btn btn-primary" href="mailto:erwinmongui@gmail.com">Email</a>', '<a class="btn btn-primary" href="mailto:erwinmongui@gmail.com">Correo</a>'),
    ('rel="noopener">LinkedIn profile</a>', 'rel="noopener">Perfil de LinkedIn</a>'),
    ('google-add-preferred-source-btn data-theme="dark" data-lang="en"', 'google-add-preferred-source-btn data-theme="dark" data-lang="es"'),

    # ---------- footer ----------
]

# Person description and ProfilePage text for the Spanish structured data.
PERSON_DESCRIPTION = ("Líder de ingeniería de software en Toronto, Canadá. Director de Tecnología y Gerente de Ingeniería "
                      "de Software en Cedar Planters, ingeniero certificado en Inteligencia Artificial, con más de 18 años "
                      "construyendo plataformas para clientes y liderando equipos de ingeniería.")
PROFILE_NAME = "Erwin Mongui, líder de ingeniería y Director de Tecnología en Toronto"
PROFILE_DESCRIPTION = ("Perfil profesional de Erwin Mongui: experiencia, impacto medido, trabajo con IA, habilidades, "
                       "educación y certificaciones.")
